/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
//Imports de todos los paquetes y librerias.
import dominio.Cliente;
import conexionesBD.Conexion;
import excepciones.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 * Pagina principal del programa
 * @author Daniel & David
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    Cliente cliente = null;
    Conexion conexion = new Conexion();

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal(Cliente cliente) {
        this.cliente = cliente;
        initComponents();
        this.txtNombre.setText(cliente.getNombre() + " " + cliente.getApellido_paterno() + " " + cliente.getApellido_materno());
        txtID.setText(String.valueOf(cliente.getId_cliente()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemTransefencia = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuDatosPersonales = new javax.swing.JMenu();
        meuEditarCuenta = new javax.swing.JMenuItem();
        menuAgregarCuenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtID.setEditable(false);

        txtNombre.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Cliente");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("ID");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Transacciones");

        menuItemTransefencia.setText("Transferencia");
        menuItemTransefencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTransefenciaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemTransefencia);

        jMenuItem2.setText("Retiro sin Cuenta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        menuDatosPersonales.setText("Editar");

        meuEditarCuenta.setText("Editar Cuenta");
        meuEditarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meuEditarCuentaActionPerformed(evt);
            }
        });
        menuDatosPersonales.add(meuEditarCuenta);

        menuAgregarCuenta.setText("Agregar Cuenta");
        menuAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarCuentaActionPerformed(evt);
            }
        });
        menuDatosPersonales.add(menuAgregarCuenta);

        jMenuBar1.add(menuDatosPersonales);

        jMenu3.setText("Salir");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuCerrarSesion.setText("Cerrar Sesión");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu3.add(menuCerrarSesion);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed
/**
 * Motodo para cerrar la sesion del menu.
 * @param evt evento
 */
    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    /**
     * Metodo para el item de transferencia, redireccion a la pantalla de trasnferencia.
     * @param evt 
     */
    private void menuItemTransefenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTransefenciaActionPerformed
        try {
            // TODO add your handling code here:
            conexion.cuentaListaTransferencia(cliente);
        } catch (PersistenciaException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemTransefenciaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            conexion.cuentaListaRetiro(cliente);
        } catch (PersistenciaException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * Metodo para seleccionar que agrega la cuenta en el menu.
     * @param evt 
     */
    private void menuAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarCuentaActionPerformed
        // TODO add your handling code here:
        RegistroCuenta registroCuenta = new RegistroCuenta(conexion.generarPresentacionesRegistrarCuenta(), cliente);
            registroCuenta.setVisible(true);
            
    }//GEN-LAST:event_menuAgregarCuentaActionPerformed

    private void meuEditarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meuEditarCuentaActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            AgregarSaldo agregarSaldo = new AgregarSaldo(cliente, conexion.generarListaCuentas(cliente));
            agregarSaldo.setVisible(true);
        } catch (PersistenciaException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_meuEditarCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menuAgregarCuenta;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenu menuDatosPersonales;
    private javax.swing.JMenuItem menuItemTransefencia;
    private javax.swing.JMenuItem meuEditarCuenta;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
